services:

  tests:
    build:
      context: .
      dockerfile: tests/Firmeza.Tests/Dockerfile
    restart: "no"

  db:
    image: postgres:16
    container_name: firmeza_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: firmeza_db
      POSTGRES_USER: firmeza_user
      POSTGRES_PASSWORD: firmeza_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U firmeza_user -d firmeza_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      tests:
        condition: service_completed_successfully

  admin:
    build:
      context: .
      dockerfile: src/Firmeza.Admin/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=firmeza_db;Username=firmeza_user;Password=firmeza_pass"
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      db:
        condition: service_healthy
      tests:
        condition: service_completed_successfully

  api:
    build:
      context: .
      dockerfile: src/Firmeza.API/Dockerfile
    ports:
      - "8081:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=firmeza_db;Username=firmeza_user;Password=firmeza_pass"
      ASPNETCORE_ENVIRONMENT: Production
      Jwt__Key: "FirmezaSecretKey2026!SuperSegura"
      Jwt__Issuer: "Firmeza.API"
      Jwt__Audience: "Firmeza.Client"
    depends_on:
      db:
        condition: service_healthy
      tests:
        condition: service_completed_successfully

  client:
    build:
      context: src/Firmeza.Client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost/api
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data: